version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: aid-backend
    volumes:
      - /data/aid:/data
    environment:
      - FS_ROOT_PATH=/data
    networks:
      - proxy
    restart: unless-stopped
    user: "1013:1013"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: aid-frontend
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
